# Generated by Django 5.0.2 on 2024-02-26 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactEnquiry',
        ),
    ]
